### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by vitaliy-tymashkov** [vitaliy-tymashkov/homepage#9]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by vitaliy-tyma** [comment]
In a landmark election result, Republican Party nominee Donald Trump swept the highest votes to be elected the 45th President of the United States.

Having won key battleground states of Florida, Ohio and North Carolina, Trump has beaten Democratic Party candidate Hillary Clinton, who was backed by incumbent President Barack Obama, in one of the most exciting elections in the United States.

Here are the top 8 qualities that make Donald Trump a great leader.

Confidence

Love him or hate him but you can’t ignore him. Donald Trump’s confidence in what he believes in makes him a perfect leader.

Even after being saddled by allegations ranging from mafia ties to unscrupulous business dealings to racial discrimination in the last four decades, Trump has confidently steered towards a landslide victory in the Presidential Elections.

Authoratitive

Trump’s authority over his subject matter is one of the qualities one must possess as a leader.

Donald Trump made it evidently clear in the run up to the elections that his foreign policy will be singularly focused on Making America Safe Again by destroying radical Islamic terrorist groups, end the nuclear deal with Iran and the ransom payments to the world’s number one state sponsor of terrorism.

He said he will end the practice of apologizing to US’ enemies and will only stand by the country’s allies. This shows authority and makes him a great leader.

Dauntless

Donald Trump has been dauntless in his criticism of what he believes in.

Earlier in the year, Trump said no one will be tougher on the Islamic State than himself if elected. According to Trump, Islamic terrorism is eating up large portions of the Middle East and that is something we would aim to completely destroy.

Deal-maker


Trump is a great negotiator and is known to understand complex deals coupled with his knowledge of a wide variety of industries and businesses.

Trump has as yet bought properties that have less of an upside. Taking risks is part of business, but Trump has been clever in ensuring the risks are calculated.

In his election campaign, he promised to cut business rate to 15 percent, reduce individual rates to three brackets of 12, 25, and 33 percent, with a 0 percent rate for many. Keeping his great deal-making abilities in mind, he may be able to bring this to life.

Prudent With Resources

Instead of hiring new people to work in government offices, Trump is proposing that nobody is able to get a job in the federal workforce for at least the next four years.

This may mean government offices that spend half their time rubber stamping offices won’t be getting any new members of staff any time soon.

One of Trump’s newest policies is to ban foreign lobbyists from fundraising for United States governments, meaning that it will be only American people and companies who will be able to have a major influence on the result of an election.

Self-interest First

Trump has been clear in his election manifesto that he intends to bring the immigration system to prioritize the interests of Americans first. Trump has proposed enforcing immigration laws – at the border and at the workplace.

He has called for building a border wall and, ending sanctuary cities, sending criminal aliens home and welcoming the immigrants who embrace the American way of life.

Clear Priorities

Trump has time and again spoken of the federal government’s duty to protect the rights of its citizens.


According to Trump, the federal government should not diminish this right by denying its’ protection.

“I am opposed to abortion except for rape, incest and life of the mother. I oppose the use of government funds to pay for abortions,” Trump has said during his election campaign.

He has also extended unwavering support to the Second Amendment right to keep and bear arms.

He has called for getting serious about prosecuting violent criminals, empowering law-abiding gun owners to defend themselves and expanding mental health programs.

This shows he has clear priorities and does not mince his words. 

Financial Understanding

Trump has a successful empire behind him, which he has led since taking over his father’s Fred Trump's real estate and construction firm, which was later renamed as The Trump Organization.

He has also been a television producer and having owned Miss USA pageants for nearly 10 years, he owns how finances must be managed.

With the trillions of dollars in debt, this is the sort of leader that might be able to turn it around for the US.
